#!/usr/bin/env python3


# Script Name               ops401 challange 26 
# Author                    Dom Moore
# Date                      11/10/20
# Description of purpose    Event Logging too P1


# Import Libraries
import time
import getpass
import cryptPass
import logging


# Declare Variable
#password = getpass.getpass("Enter your Password: \n")
pass_wd = input('Enter your Password: \n')
file_path = "/home/ubuntu/Desktop/passwd.txt"



# Define Function

def usr_wrd(): # validate password is correct
        print('Enter password')
        ps_wrd = input()
        try:
            ps_wrd = str(ps_wrd)
        except:
            print('Enter correct password ')

        if ps_wrd == pass_wd:
            print("Password valid")
        else:
            print("Password incorrect, Enter correct password! ")


logging.basicConfig(filename='file_log.txt', level=logging.INFO)
def main_pw():
    passFile = open('passwd.txt', 'r+')
    for line in passFile.readlines():
        if " " in line:
            user = line.split(';')[1]
            cyptyPass = line.split(':')[2].strip(' ')
            time.sleep(2)
            print('[*]', +user)
            testPass(cryptPass, passwd.txt)

            try:
                s.login(ipAddress, user, cyptyPass)
                login.info('Password', + cryptPass)
                break
            except cryptPass.Exception as e:
                logging.info(e)
                print('login failed')
                print(e)
    loggin.info('Finished')


# Declare functions

if __name__ == "__main__":
    print("Choose you mode Enter 1 or 2 ")
    response = int(input('Enter 1 or 2 to begin:'))

    if response == 1:
        usr_wrd()
        time.sleep(2)
        print("checking password ")
    else response == 2:
        main_pw()
        print("checking password")
        time.sleep(5)
        print("password found")



