#!/usr/bin/env python3


# Script Name               ops challange 11 p1- 401
# Author                    Dom Moore
# Date                      10/20/20
# Description of purpose    scapy tool


# Import Libraries
from scapy.all import ICMP, IP, sr1, TCP, sr
import random

# Delcare variable and port scal

host = "scanme.nmap.org"
port_range = [22:26]
#src_port = 22
#dst_port = 22


# loop
for dsp_port in port_range:
    scr_port = random.randint(1025,65534)
    port_fil =str(dsp_port)
    
    response = sr1(IP(dst=host)/TCP(sport=src_port,dport=dst_port,flags="S"),timeout=1,verbose=0)

        if responce is None:
            print("filtered packets")
        elif(responce.haslayer(TCP):
            if(response.getlayer(TCP).flags ==0x14):
                print("Not Found")
