#!/usr/bin/env python3


# Script Name               ops challange 06- 401
# Author                    Dom Moore
# Date                      10/12/20
# Description of purpose    Python Encryption





# Import Libraries

from cryptography.fernet import Fernet

# Declare Functions

def write_key():
    """
    Generates a key and save it into a file
    """
    key = Fernet.generate_key()
    with open("key.key", "wb") as key_file:
        key_file.write(key)

def load_key():
    """
    Loads the key from the current directory named `key.key`
    """
    return open("key.key", "rb").read()

# Main

# generate and write a new key
write_key()

# load the previously generated key
key = load_key()

message = "hello friend".encode()

# initialize the Fernet class
f = Fernet(key)

# encrypt the message
encrypted = f.encrypt(message)

# print how it looks
print(encrypted)
