#!/usr/bin/env python3


# Script Name               ops challange 17 p3- 401
# Author                    Dom Moore
# Date                      10/28/20
# Description of purpose    Brute Force tool p3 zipfile


# Import Libraries
import zipfile
from tqdm import tqdm

# variables for password list and file

pass_list = "password.txt"
zip_file = "opstest.zip"

# initialize zip

zip_file = zipfile.ZipFile(zip_file)

def usr_menu():
    usr_choice = ("""
        Choose your mode:
        1.password check
        2.password validation
        3.ssh login
        5.password unzip
        4.Exit
       """ )



if (usr_choice == 5):
    open_pw
else:
    exit()





# counts words in list
n_words = len(list(open(pass_list, "rb")))

print("Total passwords to test:", n_words)

# open and read words in list to check 

def open_pw():
    with open(pass_list, "rb") as pass_list:
        for word in tqdm(pass_list, total=n_words, unit="word"):
            try:
                zip_file.extractall(pwd=word.strip())
            except:
                continue
            else:
                print("Password found:", word.decode().strip())
                exit(0)
    print("Password not found .")



'''
resource: https://www.thepythoncode.com/article/crack-zip-file-password-in-python
'''
